spring:
  datasource:
    url: jdbc:h2:file:C:/Users/thales.gerhardt/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # ou 'update' para recriar as tabelas sempre ao reiniciar a aplicação
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    br:
      com:
        thalesmonteiro: DEBUG
