spring:
  datasource:
    url: jdbc:h2:file:C:/Users/thales.gerhardt/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
      format_sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    br:
      com:
        thalesmonteiro: INFO